name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] show info'
        if: ${{inputs.debug}}
        run: |
          echo "Triggered by ${{github.event_name}}"
          echo "Branch by ${{github.ref}}"
          echo "Commit sha by ${{github.sha}}"
          echo "Runner os by ${{runner.os}}"
      - name: '[debug] print from main'
        if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
        run: echo "I was triggered by main"
      - name: Greeting
        run: echo "Hello world"

