name: Test2Run

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - 'feature/**'
      - main
  workflow_dispatch:
  pull_request:

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello"
  secrets:
    NEXUS_USER: ${{ secrets.NEXUS_USER }}
