name: Test2Run

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - 'feature/**'
      - main
  workflow_dispatch:
  pull_request:

jobs:
  java-build:
    uses: ./.github/workflows/10-test.yaml
  secrets:
    NEXUS_USER: ${{ secrets.NEXUS_USER }}
